### ISSUE TITLE
No sound on videos after update

### ISSUE THREAD

**Issue by ABergelin** [cygnusx-1-org/continuum#138]
**Describe the bug**
There is no sound on redgif videos. Updated to version 8.0.0.1 yesterday to no avail.

**To Reproduce**
1. Play redgif videos
2. Should have the option for sound

**Expected behavior**
Option for sound not present

**Screenshots**

**Smartphone (please complete the following information):**
- Device: Pixel 9 Pro
- OS: Stock Android
- Version: 8.0.0.1

**Additional context**
Just wanted to add this bug as I saw in the release notes that this issue was fixed, but it still doesn't appear to be fixed.
SFW videos work as expected. Issue only appears to be with NSFW videos.

**Comment by Oriya-osmine** [comment]
Was fixed, but then they broke the fix a few days later

**Comment by marovira** [comment]
In my case, redgifs were working fine this morning and then broke around noon. In case it helps someone diagnose/fix it, here are a few more details:
* When I first moved to 8.0.0.1, I noticed that only certain videos would play without sound. These were few and far between, but what they all had in common was that URL of the video was different from the rest. Normally, the URL shown by tapping on the share button would be of the form `https://media.redgifs.com/<video-id>.mp4`. On the videos were sound did **not** work however, the URL was shown as `https://v.redd.it/<id>/DASH_1080.mp4` or `https://v.redd.it/<id>/DASH_720.mp4` depending on the video resolution.
* As of today (for me at least) all redgifs have the `v.redd.it` URL.

The root cause appears to be that Continuum is obtaining an incorrect regifs ID from somewhere, which is then causing the video URL to be incorrectly resolved. Hopefully this helps diagnose and fix the issue!

**Comment by marovira** [comment]
Quick update for those interested:
After I reported that the sound wasn't working yesterday, I restarted the app and lo and behold: the sound was restored. Note that the few random videos where sound didn't work still showed the `v.redd.it` URL even after restarting.

I was curious about this, so today I tried something new:
1. Enable auto-playing of videos and ensure they're unmuted (makes it easier to tell if there's sound).
2. Ensuring that either you're subscribed to a few subreddits with redgifs or are currently visiting one, scroll down a bit so several videos play and stop when you find a still image.
3. Now go back to the phone's home screen and leave it for a bit (I'm not sure how long it needs to be).
4. After a while, go back to Continuum and see that videos will no longer play with sound and all videos will now have the `v.redd.it` URL.

This can be "resolved" by restarting the app. 
I have no clue what's going on here, but that's what I found so far. Again, note that even when sound is restored, there are still cases where it will randomly not play any sound and will show the `v.redd.it` URL instead of the usual redgifs one.

**Comment by ABergelin** [comment]
All working now. Thanks!
